### PR TITLE
Read environment variables when doing clean install.

### PR DESCRIPTION
**Pull request by hardyjohnson**
This PR reads the existing environment variables (WARDEN_RABBITMQ, WARDEN_REDIS, WARDEN_VARNISH) and will alter the list of Magento installation flags during a clean install to align w/the configured environment.

Please let me know if you see this as useful or have comments / concerns on implementation, etc.

### CODE REVIEW

**Comment by jerrylopez** [comment]
@hardyjohnson I just tested the bootstrap command and you have access to the variables prefixed with `WARDEN_` or `TRAEFIK_`. There's a `loadEnvConfig` function where you will see how that's loaded in the warden repo here: https://github.com/davidalger/warden/blob/f638ae2c7c01d70cf4114f93cc25a8a96c133c9b/utils/env.sh#L34-L56

**Comment by hardyjohnson** [comment]
Thanks @jerrylopez, not sure what I was doing wrong when I initially had attempted that fix before, but indeed the .env WARDEN_ variables are loaded. This is now not named very well but does achieve the ability to install Magento when one or more of the three services (RabbitMQ, Redis or Varnish) are not enabled.

**Comment by hardyjohnson** [comment]
Not sure why I closed this earlier, this is better for customizing the bootstrap for different service setups.

**Comment by hardyjohnson** [comment]
Updated title and description to better reflect the current PR.

**Comment by davidalger** [comment]
Tested it out this morning along with #12 using a couple different variable configurations and it seems to work great. Thanks for the contributions!

**Pull request merged**
